name: Test Workflow By Logrus
on:
  push:
    branch:
      - master
jobs:
  First-job:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add remote server to known hosts
        run: |
          ssh-keyscan grinenko@logrus.cc ssh-keyscan
      - name: Do The Thing
        run: |
          ssh -p 11122 grinenko@logrus.cc << 'EOF'
            echo "Hello, World!\n" >> github.txt
          EOF
